### ISSUE TITLE
Configure SkipFiles

### ISSUE THREAD

**Issue by darkopetreski** [pabra/docker_awstats#20]
Is it possible to configure SkipFiles as an environment variable ?
I can solve by mounting by own copy of the awstats_env.conf but was wondering if there is another solution.
Thank you

**Comment by pabra** [comment]
Hi @darkopetreski, ideally I would like to avoid to track and maintaining environment variables for all possible awstats config variables. But there is a "joker" you should be able to use. 
On the last line of `awstats_env.conf` there is the `Include` config variable whose value will be substituted with `$AWSTATS_CONF_INCLUDE` docker ENV variable.

So you could create an awstats config with just the values you want to set:
file `my_custom_awstats.conf`
```ini
SkipHosts="abc"
SkipUserAgents="def"
```

You could then (read-only) bind mount that file in your `docker run` command or in your `docker-compose.yml` file to `/etc/awstats/my_custom_awstats.conf` and set the docker ENV variable `AWSTATS_CONF_INCLUDE` to `./my_custom_awstats.conf` (maybe the leading `./` in not needed).

Please let me know if that works for you.

**Comment by darkopetreski** [comment]
Thank you, I solved the problem.

**Comment by pabra** [comment]
Great. :) 
Would you mind to share your solution? Maybe it helps others and I'm curious too. 
In either case, if your problem is solved, please close the issue.

**Comment by darkopetreski** [comment]
I just copied awstats_env.conf in a local file, modified it and mounted in /etc/awstats/awstats_env.conf inside the container.
