### ISSUE TITLE
Please make full year view configurable

### ISSUE THREAD

**Issue by nitram84** [pabra/docker_awstats#40]
Full year view is disabled for cgi by default (AllowFullYearView=2) and this option can't be configured with an environment variable now. Please make this option configurable with an environment variable (default set to "2"). This would help a lot.

Thank you very much!

**Comment by pabra** [comment]
That's a good point @nitram84, thanks for opening this issue. I should be able to look into this within the upcoming week.

**Comment by nitram84** [comment]
Thank you very much! I prepared a pull request to fix this issue.
