### ISSUE TITLE
OpenShift support / Run awstats as non-root

### ISSUE THREAD

**Issue by nitram84** [pabra/docker_awstats#44]
I would like to run your awstats image with OpenShift, but there are some compatibility issues with your image. With some modifications of your Dockerfile I managed to run awstats on OpenShift. There are three issues:

1.) For your envsubst approach write permission to the target file is required:

`
/usr/local/bin/entrypoint.sh: line 9: can't create /etc/awstats/awstats.conf: Permission denied
`

Adding this line would fix the issue:

`
RUN touch /etc/awstats/awstats.conf && chgrp 0 /etc/awstats/awstats.conf && chmod g=u /etc/awstats/awstats.conf
`

2.) Port must be > 1024

Another port > 1024 has to be set in /usr/local/apache2/conf/awstats_httpd.conf and /usr/local/apache2/conf/httpd.conf

A configurable port using envsubst would be possible, but the workaround 1.) must be used too. On the other side a fixed port in the container shouldn't be a problem - in your example you mapped the port to 3000 anyway.

3.) Write permission to the log folder is required:

`
[Wed Nov 29 20:20:22.370985 2023] [core:error] [pid 1:tid 140445461642056] (13)Permission denied: AH00099: could not create /usr/local/apache2/logs/httpd.pid.XXXXXX
[Wed Nov 29 20:20:22.371008 2023] [core:error] [pid 1:tid 140445461642056] AH00100: httpd: could not log pid to file /usr/local/apache2/logs/httpd.pid
`

Adding this line would fix the issue:

`
RUN chgrp -R 0 /usr/local/apache2/logs/ && chmod -R g=u /usr/local/apache2/logs/
`

With these modifications your image could be used with OpenShift. Would you accept patches to support OpenShift? If yes, what would be your preferred way to fix the port issue? A fixed port e.g. 3000 ( -> breaking change ) or a configurable port (default 80) with envsubst ( -> workaround has to be used for each file with substitutions ).

Edit:

Steps to reproduce without OpenShift:

`
docker run -u 12345:0 pabra/awstats
`

**Comment by pabra** [comment]
Thanks for reporting this @nitram84. I wanted to make the listen port configurable for a long time.

**Comment by pabra** [comment]
Hi @nitram84, I think I've fixed the issues you reported. This is the diff of the changes:
https://github.com/pabra/docker_awstats/compare/f497d314db6113842d6333b09bd1f703310b2d72...master
From this I  created a new `edge` docker image. Can you please verify and report back here if image `pabra/awstats:edge`  (or explicit `pabra/awstats:master-142-fcf9446`) works for you and fixes your issues?

**Comment by nitram84** [comment]
Hi @pabra, thank you very much for your work! I tested your latest image with OpenShift 4.12.0 and I can confirm that all bugs are fixed now: Your image is now compatible with OpenShift and is working out of the box. Great work!

**Comment by pabra** [comment]
Thanks for reporting back here, @nitram84. :relaxed: 
I released a new "stable" `7.9-158-a745104` docker image.
